# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: false

# Setup
title:            Rousseau Braga
tagline:          'A Jekyll theme'
description:      'Espaço para compartilhar minhas idéias.'
url:              http://www.nuxman.com.br
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
